### PR TITLE
Bring shaders' tails before main, fixes #378

### LINKED ISSUE #378: Chrome 61 shader compiler issue
I usually use macOS with Safari so I didn't see this until recently that on a Windows box there is a compile issue that it seems if I put any of gate on the circuit, for example [this circuit](http://algassert.com/quirk#circuit=%7B%22cols%22%3A%5B%5B%22Z%5Et%22%5D%5D%7D) on a "Version 61.0.3163.79 (Official Build) beta (64-bit)" on a Windows machine I will get this: 

```
Recovered from an error. :(
Defaulted to NaN results. Computing circuit values failed. (WebGLShader: Shader compile failed.
Info: ERROR: 0:18: 'webgl_286cc28ba4512e72' : undeclared identifier
ERROR: 0:18: 'assign' : l-value required (can't modify a const)
ERROR: 0:19: 'webgl_d95d8e9804629e71' : undeclared identifier
ERROR: 0:19: 'assign' : l-value required (can't modify a const)

Source: 
precision highp float;
precision highp int;

///////////// makeFloatCoderInput(2, ketgen_ket) ////////////
uniform sampler2D _gen_ketgen_ket_tex;
uniform vec2 _gen_ketgen_ket_size;

vec2 read_ketgen_ket(float k) {
vec2 uv = vec2(mod(k, _gen_ketgen_ket_size.x) + 0.5,
floor(k / _gen_ketgen_ket_size.x) + 0.5) / _gen_ketgen_ket_size;
return texture2D(_gen_ketgen_ket_tex, uv).xy;
}

float len_ketgen_ket() {
return _gen_ketgen_ket_size.x * _gen_ketgen_ket_size.y;
}
///////////// boolInput(ketgen_control) ////////////
uniform sampler2D _gen_ketgen_control_tex;
uniform vec2 _gen_ketgen_control_size;

float read_ketgen_control(float k) {
vec2 uv = vec2(mod(k, _gen_ketgen_control_size.x) + 0.5,
floor(k / _gen_ketgen_control_size.x) + 0.5) / _gen_ketgen_control_size;
return float(texture2D(_gen_ketgen_control_tex, uv).x == 1.0);
}

float len_ketgen_control() {
return _gen_ketgen_control_size.x * _gen_ketgen_control_size.y * 4.0;
}
///////////// makeFloatCoderOutput2 ////////////
vec2 outputFor(float k);

uniform vec2 _gen_output_size;
uniform float _gen_secret_half;

float len_output() {
return _gen_output_size.x * _gen_output_size.y;
}

void main() {
vec2 xy = gl_FragCoord.xy - vec2(_gen_secret_half, _gen_secret_half);
float k = xy.y * _gen_output_size.x + xy.x;

vec2 v = outputFor(k);

gl_FragColor = vec4(v.x, v.y, 0.0, 0.0);
}
//////// tail ////////

uniform float _ketgen_step;

float _ketgen_off;
float full_out_id;

vec2 cmul(vec2 c1, vec2 c2) { return mat2(c1.x, c1.y, -c1.y, c1.x) * c2; }
vec2 inp(float k) { return read_ketgen_ket(_ketgen_off + _ketgen_step*k); }

uniform vec2 a, b, c, d;

vec2 _ketgen_output_for(float out_id, vec2 amp) {
return cmul(inp(0.0), a+(c-a)*out_id) + cmul(inp(1.0), b+(d-b)*out_id);
}

vec2 outputFor(float k) {
full_out_id = k;

float relevant_out_id = mod(floor(full_out_id / _ketgen_step), 2.0);
_ketgen_off = full_out_id - relevant_out_id*_ketgen_step;

float c = read_ketgen_control(full_out_id);
vec2 vc = read_ketgen_ket(full_out_id);
vec2 vt = _ketgen_output_for(relevant_out_id, vc);
return (1.0-c)*vc + c*vt;
})

Please report it:
Create an issue on github (requires an account) (repository: Strilanc/Quirk)
or Email the issue to craig.gidney@gmail.com


Useful details to mention (auto-included if you use the create/email links above):

Defaulted to NaN results. Computing circuit values failed.

URL
http://algassert.com/quirk#circuit={"cols":[["Z^t"]]}

BROWSER
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36
Netscape
5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36

RECOVERY DETAILS
{"circuitDefinition": {"cols": [["Z^t"]]}}

ERROR OBJECT
Error: WebGLShader: Shader compile failed.
Info: ERROR: 0:18: 'webgl_286cc28ba4512e72' : undeclared identifier
ERROR: 0:18: 'assign' : l-value required (can't modify a const)
ERROR: 0:19: 'webgl_d95d8e9804629e71' : undeclared identifier
ERROR: 0:19: 'assign' : l-value required (can't modify a const)

Source: 
precision highp float;
precision highp int;

///////////// makeFloatCoderInput(2, ketgen_ket) ////////////
uniform sampler2D _gen_ketgen_ket_tex;
uniform vec2 _gen_ketgen_ket_size;

vec2 read_ketgen_ket(float k) {
vec2 uv = vec2(mod(k, _gen_ketgen_ket_size.x) + 0.5,
floor(k / _gen_ketgen_ket_size.x) + 0.5) / _gen_ketgen_ket_size;
return texture2D(_gen_ketgen_ket_tex, uv).xy;
}

float len_ketgen_ket() {
return _gen_ketgen_ket_size.x * _gen_ketgen_ket_size.y;
}
///////////// boolInput(ketgen_control) ////////////
uniform sampler2D _gen_ketgen_control_tex;
uniform vec2 _gen_ketgen_control_size;

float read_ketgen_control(float k) {
vec2 uv = vec2(mod(k, _gen_ketgen_control_size.x) + 0.5,
floor(k / _gen_ketgen_control_size.x) + 0.5) / _gen_ketgen_control_size;
return float(texture2D(_gen_ketgen_control_tex, uv).x == 1.0);
}

float len_ketgen_control() {
return _gen_ketgen_control_size.x * _gen_ketgen_control_size.y * 4.0;
}
///////////// makeFloatCoderOutput2 ////////////
vec2 outputFor(float k);

uniform vec2 _gen_output_size;
uniform float _gen_secret_half;

float len_output() {
return _gen_output_size.x * _gen_output_size.y;
}

void main() {
vec2 xy = gl_FragCoord.xy - vec2(_gen_secret_half, _gen_secret_half);
float k = xy.y * _gen_output_size.x + xy.x;

vec2 v = outputFor(k);

gl_FragColor = vec4(v.x, v.y, 0.0, 0.0);
}
//////// tail ////////

uniform float _ketgen_step;

float _ketgen_off;
float full_out_id;

vec2 cmul(vec2 c1, vec2 c2) { return mat2(c1.x, c1.y, -c1.y, c1.x) * c2; }
vec2 inp(float k) { return read_ketgen_ket(_ketgen_off + _ketgen_step*k); }

uniform vec2 a, b, c, d;

vec2 _ketgen_output_for(float out_id, vec2 amp) {
return cmul(inp(0.0), a+(c-a)*out_id) + cmul(inp(1.0), b+(d-b)*out_id);
}

vec2 outputFor(float k) {
full_out_id = k;

float relevant_out_id = mod(floor(full_out_id / _ketgen_step), 2.0);
_ketgen_off = full_out_id - relevant_out_id*_ketgen_step;

float c = read_ketgen_control(full_out_id);
vec2 vc = read_ketgen_ket(full_out_id);
vec2 vt = _ketgen_output_for(relevant_out_id, vc);
return (1.0-c)*vc + c*vt;
}

ERROR LOCATION
Error: WebGLShader: Shader compile failed.
Info: ERROR: 0:18: 'webgl_286cc28ba4512e72' : undeclared identifier
ERROR: 0:18: 'assign' : l-value required (can't modify a const)
ERROR: 0:19: 'webgl_d95d8e9804629e71' : undeclared identifier
ERROR: 0:19: 'assign' : l-value required (can't modify a const)

Source: 
precision highp float;
precision highp int;

///////////// makeFloatCoderInput(2, ketgen_ket) ////////////
uniform sampler2D _gen_ketgen_ket_tex;
uniform vec2 _gen_ketgen_ket_size;

vec2 read_ketgen_ket(float k) {
vec2 uv = vec2(mod(k, _gen_ketgen_ket_size.x) + 0.5,
floor(k / _gen_ketgen_ket_size.x) + 0.5) / _gen_ketgen_ket_size;
return texture2D(_gen_ketgen_ket_tex, uv).xy;
}

float len_ketgen_ket() {
return _gen_ketgen_ket_size.x * _gen_ketgen_ket_size.y;
}
///////////// boolInput(ketgen_control) ////////////
uniform sampler2D _gen_ketgen_control_tex;
uniform vec2 _gen_ketgen_control_size;

float read_ketgen_control(float k) {
vec2 uv = vec2(mod(k, _gen_ketgen_control_size.x) + 0.5,
floor(k / _gen_ketgen_control_size.x) + 0.5) / _gen_ketgen_control_size;
return float(texture2D(_gen_ketgen_control_tex, uv).x == 1.0);
}

float len_ketgen_control() {
return _gen_ketgen_control_size.x * _gen_ketgen_control_size.y * 4.0;
}
///////////// makeFloatCoderOutput2 ////////////
vec2 outputFor(float k);

uniform vec2 _gen_output_size;
uniform float _gen_secret_half;

float len_output() {
return _gen_output_size.x * _gen_output_size.y;
}

void main() {
vec2 xy = gl_FragCoord.xy - vec2(_gen_secret_half, _gen_secret_half);
float k = xy.y * _gen_output_size.x + xy.x;

vec2 v = outputFor(k);

gl_FragColor = vec4(v.x, v.y, 0.0, 0.0);
}
//////// tail ////////

uniform float _ketgen_step;

float _ketgen_off;
float full_out_id;

vec2 cmul(vec2 c1, vec2 c2) { return mat2(c1.x, c1.y, -c1.y, c1.x) * c2; }
vec2 inp(float k) { return read_ketgen_ket(_ketgen_off + _ketgen_step*k); }

uniform vec2 a, b, c, d;

vec2 _ketgen_output_for(float out_id, vec2 amp) {
return cmul(inp(0.0), a+(c-a)*out_id) + cmul(inp(1.0), b+(d-b)*out_id);
}

vec2 outputFor(float k) {
full_out_id = k;

float relevant_out_id = mod(floor(full_out_id / _ketgen_step), 2.0);
_ketgen_off = full_out_id - relevant_out_id*_ketgen_step;

float c = read_ketgen_control(full_out_id);
vec2 vc = read_ketgen_ket(full_out_id);
vec2 vt = _ketgen_output_for(relevant_out_id, vc);
return (1.0-c)*vc + c*vt;
}
at Function.compileShader (http://algassert.com/quirk:2956:110)
at new e (http://algassert.com/quirk:2946:453)
at a.initializer (http://algassert.com/quirk:2941:66)
at a.initializedValue (http://algassert.com/quirk:2932:79)
at a.renderToFunc (http://algassert.com/quirk:2943:122)
at a.renderTo (http://algassert.com/quirk:2903:126)
at a.renderToFunc (http://algassert.com/quirk:2842:76)
at a.renderTo (http://algassert.com/quirk:2903:126)
at b.shadeAndTrade (http://algassert.com/quirk:2995:3)
at b.applyOperation (http://algassert.com/quirk:1285:115)

COVERED
(Recovered) Defaulted to NaN results. Computing circuit values failed. @ Error: WebGLShader: Shader compile failed.
Info: ERROR: 0:18: 'webgl_286cc28ba4512e72' : undeclared identifier
ERROR: 0:18: 'assign' : l-value required (can't modify a const)
ERROR: 0:[...]

PRE-DRAWN 
```

### PR DESCRIPTION
**Pull request by ebraminio**
Obviously a hack but as Chrome reaches 61, Quirk will be broken without it so possibly a temporary solution.

### CODE REVIEW

**Comment by ebraminio** [comment]
This obviously a hack from design standpoint but as Chrome 61 is going to be released very soon and the fix will be available till 63 or 62, please consider some fix for it, or temporarily applying this till release of Chrome 63.

**Comment by Strilanc** [comment]
Yeah, it started breaking on my work machine today so I can finally test it for myself. Once it's fixed there will be some delay as I try to get some other features in and test the new release on a whole bunch of machines. I'm in the middle of a move, but I'll try to deal with it this weekend.

**Comment by Strilanc** [comment]
Not sure what's wrong with the travis check. Tests pass locally without timing out. Will investigate separately.

**Comment by ebraminio** [comment]
Great. Thanks for the creation and development of this awesome work :)

**Pull request merged**
