### PR TITLE
Solved problems with touch events (Android+Chrome). Issue #29

### PR DESCRIPTION
**Pull request by perak**
@Strilanc solution was super-simple: no code, only css property `touch-action: none;` set to `<canvas id="drawCanvas">`

### CODE REVIEW

**Comment by perak** [comment]
Now drag&drop works perfectly, but pan/zoom on the canvas doesn't work.

I think pan&zoom should be implemented via code instead using browser's default behavior (much easier than fight with browser incompatibility/inconsistency).

**Comment by Strilanc** [comment]
Changing the browser's scrolling behavior is one of the things people *hate*. It feels very unnatural when the momentum/friction/slowdown suddenly changes.

I do think `touch-action` will be part of the solution. It can probably solve the related "Oops, I missed the gate and the browser interpreted drag-down as 'reload the page'. Bye bye undo history." issue.

I wonder what happens if the property is changed during the touch? Maybe the browser will interpret actively changing touch-action to none on touchdown as "I want control of this touch!".

**Comment by perak** [comment]
@Strilanc if I remember well, while digging docs trying to solve this issue, changing touch-action after `touchstart` is forbidden by the standard (and browser should ignore it), but I'll try it later when I find some free time.

If that's impossible, then we need to implement pan function - if target is not the gate, touchmove scrolls, if gate is under finger - touchmove drags.

**Comment by Strilanc** [comment]
I took the idea from this PR and ran with it. I placed invisible divs with touch-action: none over all the draggable boxes. https://github.com/Strilanc/Quirk/commit/fcc7888371f28596c3af4b9718a88b29e9fc432b

So I won't be merging this, but I did end up using the idea. Thanks!

**Comment by perak** [comment]
Great, glad you (or we, or however) solved it - now I'll be able to play with simulator on my tablet.

P.S. thanks for your work! This thing is best quantum computer emulator today, and it helped me a lot to unerstand and learn about quantum algorithms.

(and with this fix, quantum computer emulator is available from the pocket to whole humankind, good job!)

**Pull request closed without merging**
